begin;
create extension if not exists pgtap with schema extensions;
set local search_path=extensions,public,private;
select no_plan();
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data) values
('90620000-0000-4000-8000-000000000001','authenticated','authenticated','assistance-editor@example.test','{}','{}'),
('90630000-0000-4000-8000-000000000002','authenticated','authenticated','assistance-outsider@example.test','{}','{}');
insert into profiles(id,display_name,role) values ('90620000-0000-4000-8000-000000000001','Editor','admin'),('90630000-0000-4000-8000-000000000002','Outsider','learner') on conflict(id) do update set role=excluded.role;
insert into courses(id,slug,title,description,category,catalog_scope,status) values('assistance-course','assistance-course','Community','Working together','Values','platform','draft');
insert into lessons(id,slug,course_id,title,status) values('assistance-lesson','assistance-lesson','assistance-course','Listening','draft');
insert into lesson_pages(id,lesson_id,page_number,title,page_type) values('assistance-page','assistance-lesson',1,'Listen first','concept');
insert into lesson_content_blocks(page_id,block_type,sort_order,payload) values('assistance-page','text',1,'{"body":"Hear every person before choosing an action."}');
create function pg_temp.ready(p_result uuid,p_candidate jsonb) returns void language plpgsql as $$
declare j public.ai_generation_jobs;
begin
 select * into j from public.service_claim_ai_page(p_result,'assistance-test');
 perform public.service_ai_page_checkpoint(j.id,'assistance-test',j.lock_token,j.lock_version,'begin');
 perform public.service_ai_page_checkpoint(j.id,'assistance-test',j.lock_token,j.lock_version,'ready',p_candidate);
end $$;
select set_config('test.quiz','{"title":"Listening questions","questions":[{"prompt":"What should happen first?","questionType":"single_choice","explanation":"Listen before choosing an action.","xp":10,"options":[{"label":"Listen to everyone","isCorrect":true},{"label":"Choose without listening","isCorrect":false}]},{"prompt":"Whose views should we hear?","questionType":"single_choice","explanation":"Hear every person.","xp":10,"options":[{"label":"Every person","isCorrect":true},{"label":"Only the loudest person","isCorrect":false}]}]}',true);
select set_config('test.plan','{"title":"Next lessons","suggestions":[{"title":"Making a fair choice","description":"Compare options after listening.","reason":"Adds decision making after listening."}]}',true);
select set_config('test.draft','{"title":"Making a fair choice","description":"Compare options after listening.","pages":[{"title":"Compare options","subtitle":"Consider everyone","pageType":"scenario","blocks":[{"blockType":"text","payload":{"body":"Compare how each option affects people."}},{"blockType":"image","payload":{"mediaIntent":{"version":1,"kind":"image","purpose":"Compare two choices","aspectRatio":"16:9","required":false,"style":"inherit"}}}]}]}',true);
select ok(not has_function_privilege('authenticated','private.validate_ai_assistance(text,jsonb,integer)','execute'),'candidate validator is private');
select ok(not has_function_privilege('anon','public.admin_quote_ai_assistance(text,text,text,text,integer,uuid,text,integer)','execute'),'anonymous quotes denied');
select set_config('request.jwt.claim.sub','90620000-0000-4000-8000-000000000001',true);
set local role authenticated;
select throws_ok($$select public.admin_quote_ai_assistance('assistance-course','quiz','assistance-lesson','',4)$$,'22023','Choose a valid request.','bounded quiz count');
select set_config('test.q',public.admin_quote_ai_assistance('assistance-course','quiz','assistance-lesson','',2)->>'id',true);
select is(public.admin_read_ai_results(current_setting('test.q')::uuid)->>'estimatedUnits','40','quiz cost uses existing formula');
select ok(not(public.admin_read_ai_results(current_setting('test.q')::uuid) ? 'context'),'private teaching context not projected');
select is(public.admin_start_ai_page(current_setting('test.q')::uuid)->>'stage','starting','quiz start accepted');
select is(public.admin_start_ai_page(current_setting('test.q')::uuid)->>'stage','starting','start retry reuses intent');
reset role;
select is((select count(*) from ai_generation_jobs where prompt->>'operationId'=current_setting('test.q')),1::bigint,'one durable job');
select ok((select context::text like '%Hear every person%' from private.ai_authoring_results where id=current_setting('test.q')::uuid),'quiz receives actual teaching excerpts');
select lives_ok($$select pg_temp.ready(current_setting('test.q')::uuid,current_setting('test.quiz')::jsonb)$$,'quiz provider checkpoints validate');
select is((select count(*) from quiz_questions q join quizzes z on z.id=q.quiz_id where z.lesson_id='assistance-lesson'),0::bigint,'generation does not insert questions');
set local role authenticated;
select throws_ok($$select public.admin_apply_ai_page(current_setting('test.q')::uuid)$$,'42501','Page result unavailable.','quiz cannot bypass page apply boundary');
select throws_ok($$select public.admin_prepare_ai_page_apply(current_setting('test.q')::uuid)$$,'42501','Page result unavailable.','quiz cannot prepare page apply');
select throws_ok($$select public.admin_prepare_ai_assistance_apply(current_setting('test.q')::uuid,array[0,0])$$,'22023','Select the items to add.','duplicate selection rejected');
select lives_ok($$select public.admin_prepare_ai_assistance_apply(current_setting('test.q')::uuid,array[1])$$,'explicit selected question retained');
select is(public.admin_read_ai_results(current_setting('test.q')::uuid)->>'applicationState','checking','navigation exposes checking save');
select throws_ok($$select public.admin_prepare_ai_assistance_apply(current_setting('test.q')::uuid,array[0])$$,'PT409','Check the earlier save before changing your selection.','selection immutable after save accepted');
select set_config('test.receipt',public.admin_apply_ai_assistance(current_setting('test.q')::uuid)::text,true);
select is(current_setting('test.receipt')::jsonb->>'status','saved','quiz application commits');
select is(public.admin_apply_ai_assistance(current_setting('test.q')::uuid),current_setting('test.receipt')::jsonb,'receipt replay is exact');
reset role;
select is((select count(*) from quiz_questions q join quizzes z on z.id=q.quiz_id where z.lesson_id='assistance-lesson'),1::bigint,'only selected question added once');
select is((select prompt from quiz_questions q join quizzes z on z.id=q.quiz_id where z.lesson_id='assistance-lesson'),'Whose views should we hear?','correct selection inserted');
select is((select xp from quiz_questions q join quizzes z on z.id=q.quiz_id where z.lesson_id='assistance-lesson'),10,'question XP unchanged');
select set_config('request.jwt.claim.sub','90630000-0000-4000-8000-000000000002',true);
set local role authenticated;
select throws_ok($$select public.admin_read_ai_results(current_setting('test.q')::uuid)$$,'42501','Result unavailable.','outsider cannot read quiz');
select throws_ok($$select public.admin_apply_ai_assistance(current_setting('test.q')::uuid)$$,'42501','Result unavailable.','receipt does not bypass access');
reset role;
select set_config('request.jwt.claim.sub','90620000-0000-4000-8000-000000000001',true);
set local role authenticated;
select set_config('test.planId',public.admin_quote_ai_assistance('assistance-course','lesson_plan')->>'id',true);
select is(public.admin_read_ai_results(current_setting('test.planId')::uuid)->>'estimatedUnits','47','plan quoted separately');
select public.admin_start_ai_page(current_setting('test.planId')::uuid);
reset role;
select lives_ok($$select pg_temp.ready(current_setting('test.planId')::uuid,current_setting('test.plan')::jsonb)$$,'lesson plan checkpoints validate');
set local role authenticated;
select throws_ok($$select public.admin_prepare_ai_assistance_apply(current_setting('test.planId')::uuid,array[0])$$,'PT409','This result cannot be added.','plan must be drafted before application');
select set_config('test.draftId',public.admin_quote_ai_assistance('assistance-course','lesson_draft',null,'',1,current_setting('test.planId')::uuid,'',0)->>'id',true);
select is(public.admin_read_ai_results(current_setting('test.draftId')::uuid)->>'estimatedUnits','135','draft cost quoted separately');
select public.admin_start_ai_page(current_setting('test.draftId')::uuid);
reset role;
select lives_ok($$select pg_temp.ready(current_setting('test.draftId')::uuid,current_setting('test.draft')::jsonb)$$,'lesson draft and real placeholder validate');
select is((select count(*) from lessons where course_id='assistance-course'),1::bigint,'ready lesson is not inserted automatically');
set local role authenticated;
select public.admin_prepare_ai_assistance_apply(current_setting('test.draftId')::uuid,array[0]);
select set_config('test.draftReceipt',public.admin_apply_ai_assistance(current_setting('test.draftId')::uuid)::text,true);
select is(current_setting('test.draftReceipt')::jsonb->>'status','saved','lesson saves');
select is(public.admin_apply_ai_assistance(current_setting('test.draftId')::uuid),current_setting('test.draftReceipt')::jsonb,'lesson replay idempotent');
reset role;
select is((select count(*) from lessons where course_id='assistance-course'),2::bigint,'one draft lesson appended');
select is((select status from lessons where id=current_setting('test.draftReceipt')::jsonb->>'lessonId'),'draft','lesson never auto published');
select is((select ai_text_status from lessons where id=current_setting('test.draftReceipt')::jsonb->>'lessonId'),'draft','text needs review');
select is((select count(*) from learning_media_assets where course_id='assistance-course'),0::bigint,'text generation creates no media assets');
select is((select count(*) from ai_generation_jobs where entity_id='assistance-course' and job_type='media_assets'),0::bigint,'text generation starts no image jobs');
select set_config('test.rev',(select draft_revision::text from lessons where id=current_setting('test.draftReceipt')::jsonb->>'lessonId'),true);
set local role authenticated;
select lives_ok($$select public.admin_review_ai_assistance_lesson(current_setting('test.draftReceipt')::jsonb->>'lessonId',current_setting('test.rev')::bigint)$$,'normal explicit review works without legacy media seeds');
reset role;
select is((select ai_publish_status from lessons where id=current_setting('test.draftReceipt')::jsonb->>'lessonId'),'ready','review records readiness');
-- Stale snapshots and quote starts never overwrite manual changes.
set local role authenticated;
select set_config('test.stale',public.admin_quote_ai_assistance('assistance-course','quiz','assistance-lesson')->>'id',true);
select public.admin_start_ai_page(current_setting('test.stale')::uuid);
reset role;
select pg_temp.ready(current_setting('test.stale')::uuid,jsonb_set(current_setting('test.quiz')::jsonb,'{questions}',jsonb_build_array(current_setting('test.quiz')::jsonb->'questions'->0)));
update lesson_content_blocks set payload='{"body":"Updated manual teaching."}' where page_id='assistance-page';
set local role authenticated;
select public.admin_prepare_ai_assistance_apply(current_setting('test.stale')::uuid,array[0]);
select is(public.admin_apply_ai_assistance(current_setting('test.stale')::uuid)->>'status','not_saved','stale draft rejected with durable outcome');
select is(public.admin_read_ai_results(current_setting('test.stale')::uuid)->>'applicationState','not_saved','recovery distinguishes confirmed failure');
select set_config('test.stop',public.admin_quote_ai_assistance('assistance-course','lesson_plan')->>'id',true);
select public.admin_start_ai_page(current_setting('test.stop')::uuid);
select is(public.admin_stop_ai_result(current_setting('test.stop')::uuid)->>'stage','stopped','stop settles non-page generation');
select lives_ok($$select public.admin_delete_ai_result(current_setting('test.q')::uuid)$$,'delete candidate independently of saved quiz');
select is(public.admin_read_ai_results(current_setting('test.q')::uuid)->'receipt'->>'status','saved','deletion retains saved receipt');
reset role;
select throws_ok($$select private.validate_ai_assistance('quiz',jsonb_set(current_setting('test.quiz')::jsonb,'{questions,0,options,1,isCorrect}','true'),2)$$,'22023','Check the answer options.','multiple correct answers rejected');
select throws_ok($$select private.validate_ai_assistance('lesson_draft',jsonb_set(current_setting('test.draft')::jsonb,'{pages,0,blocks,1,payload,src}','"https://example.test/not-an-asset"'),1)$$,'22023','Only optional media placeholders are allowed.','fabricated asset URL rejected');

-- All three operations retain existing organisation reservation and settlement rules.
insert into organizations(id,slug,name,status,created_by) values('90620000-0000-4000-8000-000000000101','assistance-org','Assistance org','published','90620000-0000-4000-8000-000000000001');
insert into organization_memberships(organization_id,user_id,role,status) values('90620000-0000-4000-8000-000000000101','90620000-0000-4000-8000-000000000001','organisation_owner','active');
insert into courses(id,slug,title,description,category,catalog_scope,organization_id,status) values('assistance-org-course','assistance-org-course','Org course','Teaching','Values','organization_private','90620000-0000-4000-8000-000000000101','draft');
insert into lessons(id,slug,course_id,title,status) values('assistance-org-lesson','assistance-org-lesson','assistance-org-course','Listening','draft');
insert into lesson_pages(id,lesson_id,page_number,title,page_type) values('assistance-org-page','assistance-org-lesson',1,'Listen','concept');
insert into lesson_content_blocks(page_id,block_type,sort_order,payload) values('assistance-org-page','text',1,'{"body":"Listen before choosing."}');
set local role authenticated;
select public.admin_upsert_organization_temporary_entitlement_grant(null,'90620000-0000-4000-8000-000000000101','granular_override',null,
 '{"ai_authoring_enabled":true,"ai_monthly_allocation":250,"ai_hard_limit":250,"ai_user_rate_limit_per_day":20,"ai_organization_concurrency_limit":3,"allowed_ai_operation_types":["ai_quiz_question_generation","ai_planner_expand_course","ai_lesson_extension"],"allowed_ai_roles":["organisation_owner"]}',
 now()-interval '1 minute',now()+interval '1 day','Assistance fixture');
select set_config('test.orgplan',public.admin_quote_ai_assistance('assistance-org-course','lesson_plan')->>'id',true);
select public.admin_start_ai_page(current_setting('test.orgplan')::uuid);
select public.admin_start_ai_page(current_setting('test.orgplan')::uuid);
reset role;
select is((select sum(reserved_units) from organization_ai_usage_records where organization_id='90620000-0000-4000-8000-000000000101'),47::numeric,'plan reserves once using existing metering');
select lives_ok($$select pg_temp.ready(current_setting('test.orgplan')::uuid,current_setting('test.plan')::jsonb)$$,'organisation plan worker accepts existing operation/job type');
set local role authenticated;
select is(public.admin_read_ai_results(current_setting('test.orgplan')::uuid)->'credit'->>'used','47','plan charge settled');
select set_config('test.orgdraft',public.admin_quote_ai_assistance('assistance-org-course','lesson_draft',null,'',1,current_setting('test.orgplan')::uuid,'',0)->>'id',true);
select public.admin_start_ai_page(current_setting('test.orgdraft')::uuid);
reset role;
select lives_ok($$select pg_temp.ready(current_setting('test.orgdraft')::uuid,current_setting('test.draft')::jsonb)$$,'organisation lesson draft worker accepts existing operation');
set local role authenticated;
select public.admin_prepare_ai_assistance_apply(current_setting('test.orgdraft')::uuid,array[0]);
select is(public.admin_apply_ai_assistance(current_setting('test.orgdraft')::uuid)->>'status','saved','organisation draft applies without new generation');
select public.admin_apply_ai_assistance(current_setting('test.orgdraft')::uuid);
select set_config('test.orgquiz',public.admin_quote_ai_assistance('assistance-org-course','quiz','assistance-org-lesson')->>'id',true);
select public.admin_start_ai_page(current_setting('test.orgquiz')::uuid);
select is(public.admin_stop_ai_result(current_setting('test.orgquiz')::uuid)->'credit'->>'status','released','quiz stop before provider releases credit');
reset role;
select is((select sum(final_charged_units) from organization_ai_usage_records where organization_id='90620000-0000-4000-8000-000000000101'),182::numeric,'plan plus draft charge once; quiz stopped without charge');

-- A confirmed database failure rolls back all content and exposes a durable failure.
set local role authenticated;
select set_config('test.dbfailure',public.admin_quote_ai_assistance('assistance-course','quiz','assistance-lesson')->>'id',true);
select public.admin_start_ai_page(current_setting('test.dbfailure')::uuid);
reset role;
select pg_temp.ready(current_setting('test.dbfailure')::uuid,jsonb_set(current_setting('test.quiz')::jsonb,'{questions}',jsonb_build_array(current_setting('test.quiz')::jsonb->'questions'->0)));
create function pg_temp.fail_fixture_option() returns trigger language plpgsql as $$begin raise exception 'Injected storage failure'; end$$;
create trigger assistance_fixture_failure before insert on quiz_options for each row execute function pg_temp.fail_fixture_option();
set local role authenticated;
select public.admin_prepare_ai_assistance_apply(current_setting('test.dbfailure')::uuid,array[0]);
select is(public.admin_apply_ai_assistance(current_setting('test.dbfailure')::uuid)->>'status','not_saved','unexpected failure returns confirmed not saved');
select is(public.admin_read_ai_results(current_setting('test.dbfailure')::uuid)->>'applicationState','not_saved','database failure is recoverable after navigation');
reset role;
select is((select count(*) from quiz_questions q join quizzes z on z.id=q.quiz_id where z.lesson_id='assistance-lesson'),1::bigint,'failed option insert leaves no partial question');
drop trigger assistance_fixture_failure on quiz_options;
set local role authenticated;
select is(public.admin_apply_ai_assistance(current_setting('test.dbfailure')::uuid)->>'status','saved','same application identity retries after confirmed failure');
reset role;
-- Tenant member, rather than a platform admin, can recover only their own workspace.
update profiles set role='learner' where id='90620000-0000-4000-8000-000000000001';
set local role authenticated;
select lives_ok($$select public.admin_read_ai_results(current_setting('test.orgplan')::uuid)$$,'organisation owner can recover own suggestion');
select throws_ok($$select public.admin_read_ai_results(current_setting('test.planId')::uuid)$$,'42501','Result unavailable.','organisation owner cannot read platform candidate');
reset role;
update organization_memberships set status='suspended' where organization_id='90620000-0000-4000-8000-000000000101' and user_id='90620000-0000-4000-8000-000000000001';
set local role authenticated;
select throws_ok($$select public.admin_apply_ai_assistance(current_setting('test.orgdraft')::uuid)$$,'42501','Result unavailable.','membership loss blocks saved receipt replay');
reset role;
select * from finish();
rollback;
