begin;
create extension if not exists pgtap with schema extensions;
set local search_path=extensions,public,private;
select no_plan();
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data) values
('90640000-0000-4000-8000-000000000001','authenticated','authenticated','course-editor@example.test','{}','{}'),
('90650000-0000-4000-8000-000000000002','authenticated','authenticated','course-outsider@example.test','{}','{}');
insert into profiles(id,display_name,role) values ('90640000-0000-4000-8000-000000000001','Editor','admin'),('90650000-0000-4000-8000-000000000002','Outsider','learner') on conflict(id) do update set role=excluded.role;
select set_config('test.outline','{"title":"Community choices","description":"Listen and choose fairly.","lessons":[{"title":"Listen first","description":"Hear everyone."},{"title":"Choose fairly","description":"Compare effects."}]}',true);
select set_config('test.brief','{"need":"Fair decisions","audience":"Adults","tone":"Direct","lessonCount":2}',true);
select set_config('test.lesson','{"title":"Listen first","description":"Hear everyone.","pages":[{"title":"Listen","subtitle":"","pageType":"concept","blocks":[{"blockType":"text","payload":{"body":"Hear everyone before choosing."}},{"blockType":"image","payload":{"src":"","mediaIntent":{"version":1,"kind":"image","purpose":"A listening circle","aspectRatio":"16:9","required":false,"style":"inherit"}}}]}],"questions":[]}',true);
create function pg_temp.step(p_id uuid,p_action text,p_value jsonb default null) returns jsonb language plpgsql as $$
declare j public.ai_generation_jobs;
begin
 select * into j from ai_generation_jobs where id=(select job_id from private.ai_authoring_results where id=p_id);
 if j.status='queued' then select * into j from public.service_claim_ai_page(p_id,'course-test'); end if;
 return public.service_ai_course_checkpoint(j.id,'course-test',j.lock_token,j.lock_version,p_action,p_value);
end $$;
select ok(not has_function_privilege('authenticated','private.materialize_ai_course_tree(text,jsonb,jsonb,jsonb,jsonb,jsonb,jsonb,jsonb,jsonb,jsonb)','execute'),'atomic core stays private');
select ok(not has_function_privilege('authenticated','public.service_ai_course_checkpoint(uuid,text,uuid,integer,text,jsonb)','execute'),'worker checkpoint is service-only');
select ok(not has_function_privilege('anon','public.admin_quote_ai_course(text,jsonb,uuid,integer,integer,text,boolean,uuid)','execute'),'anonymous outline quote denied');
select set_config('request.jwt.claim.sub','90640000-0000-4000-8000-000000000001',true);
set local role authenticated;
select set_config('test.outlineId',public.admin_quote_ai_course('course_outline',current_setting('test.brief')::jsonb)->>'id',true);
select is(public.admin_read_ai_results(current_setting('test.outlineId')::uuid)->>'estimatedUnits','57','one outline has separate quote');
select is(public.admin_read_ai_results(current_setting('test.outlineId')::uuid)->>'courseId',null,'outline needs no course');
select public.admin_start_ai_page(current_setting('test.outlineId')::uuid);
select is(public.admin_start_ai_page(current_setting('test.outlineId')::uuid)->>'stage','starting','start identity is idempotent');
reset role;
select pg_temp.step(current_setting('test.outlineId')::uuid,'begin');
select lives_ok($$select pg_temp.step(current_setting('test.outlineId')::uuid,'checkpoint',current_setting('test.outline')::jsonb)$$,'single outline checkpoint persists');
set local role authenticated;
select is(jsonb_array_length(public.admin_read_ai_results(current_setting('test.outlineId')::uuid)->'outline'->'lessons'),2,'outline recovered by result ID');
select ok(exists(select 1 from jsonb_array_elements(public.admin_read_ai_results()->'items') i where i->>'id'=current_setting('test.outlineId')),'outline discoverable without course');
select set_config('test.oldQuote',public.admin_quote_ai_course('course_draft',null,current_setting('test.outlineId')::uuid,1,0)->>'id',true);
select public.admin_save_ai_course_outline(current_setting('test.outlineId')::uuid,1,current_setting('test.outline')::jsonb);
select throws_ok($$select public.admin_start_ai_page(current_setting('test.oldQuote')::uuid)$$,'PT409','The outline changed. Check the cost again.','editing invalidates stale draft cost');
select throws_ok($$select public.admin_save_ai_course_outline(current_setting('test.outlineId')::uuid,1,current_setting('test.outline')::jsonb)$$,'PT409','The outline changed. Reopen it before saving.','concurrent outline edit fenced');
select set_config('test.draftId',public.admin_quote_ai_course('course_draft',null,current_setting('test.outlineId')::uuid,2,0)->>'id',true);
select is(public.admin_read_ai_results(current_setting('test.draftId')::uuid)->>'estimatedUnits','170','draft estimate excludes unselected quizzes');
select public.admin_start_ai_page(current_setting('test.draftId')::uuid);
reset role;
select is(pg_temp.step(current_setting('test.draftId')::uuid,'begin')->>'index','0','first missing lesson starts');
select pg_temp.step(current_setting('test.draftId')::uuid,'checkpoint',current_setting('test.lesson')::jsonb);
select is((select jsonb_array_length(candidate->'completed') from private.ai_authoring_results where id=current_setting('test.draftId')::uuid),1,'valid first lesson durably checkpointed');
select is((select count(*) from courses where id='course-ai-'||replace(current_setting('test.draftId'),'-','')),0::bigint,'checkpoint creates no editable course');
select is(pg_temp.step(current_setting('test.draftId')::uuid,'begin')->>'index','1','next lesson starts');
select throws_ok($$select pg_temp.step(current_setting('test.draftId')::uuid,'begin')$$,'P0001','An earlier provider outcome is uncertain; it cannot be replayed.','uncertain paid call never automatically repeated');
select pg_temp.step(current_setting('test.draftId')::uuid,'failed');
set local role authenticated;
select is(public.admin_read_ai_results(current_setting('test.draftId')::uuid)->>'completedCount','1','partial failure retains completed preview');
select set_config('test.retryId',public.admin_quote_ai_course('course_draft',null,current_setting('test.draftId')::uuid,0,0,'',true)->>'id',true);
select is(public.admin_read_ai_results(current_setting('test.retryId')::uuid)->>'estimatedUnits','135','retry quotes only one unfinished lesson plus request base');
select public.admin_start_ai_page(current_setting('test.retryId')::uuid);
reset role;
select set_config('test.retryContext',pg_temp.step(current_setting('test.retryId')::uuid,'begin')::text,true);
select is(current_setting('test.retryContext')::jsonb->>'index','1','retry skips completed lesson');
select is(current_setting('test.retryContext')::jsonb->'completed'->0->'lesson',current_setting('test.lesson')::jsonb,'retry worker receives the actual retained teaching checkpoint');
select is(current_setting('test.retryContext')::jsonb->'outline',(select course_outline from private.ai_authoring_results where id=current_setting('test.retryId')::uuid),'worker receives the accepted edited progression');
select is(current_setting('test.retryContext')::jsonb->'brief',current_setting('test.brief')::jsonb,'worker receives the original audience and learning need');
select pg_temp.step(current_setting('test.retryId')::uuid,'checkpoint',jsonb_set(current_setting('test.lesson')::jsonb,'{title}','"Choose fairly"'));
set local role authenticated;
select is(public.admin_read_ai_results(current_setting('test.retryId')::uuid)->>'completedCount','2','recovered version contains both lessons');
select public.admin_prepare_ai_course_apply(current_setting('test.retryId')::uuid);
select set_config('test.receipt',public.admin_apply_ai_course(current_setting('test.retryId')::uuid)::text,true);
select is(current_setting('test.receipt')::jsonb->>'status','saved','course atomically materializes');
select is(public.admin_apply_ai_course(current_setting('test.retryId')::uuid),current_setting('test.receipt')::jsonb,'receipt replay exact');
reset role;
select is((select count(*) from lessons where course_id=current_setting('test.receipt')::jsonb->>'courseId'),2::bigint,'exactly two lessons saved');
select is((select status::text from courses where id=current_setting('test.receipt')::jsonb->>'courseId'),'draft','no automatic publication');
select is((select ai_text_status from courses where id=current_setting('test.receipt')::jsonb->>'courseId'),'draft','no automatic approval');
select is((select count(*) from quizzes q join lessons l on l.id=q.lesson_id where l.course_id=current_setting('test.receipt')::jsonb->>'courseId'),0::bigint,'no unselected quizzes created');
select is((select count(*) from learning_media_assets where course_id=current_setting('test.receipt')::jsonb->>'courseId'),0::bigint,'zero generated media assets');
select set_config('request.jwt.claim.sub','90650000-0000-4000-8000-000000000002',true);
set local role authenticated;
select throws_ok($$select public.admin_read_ai_results(current_setting('test.outlineId')::uuid)$$,'42501','Result unavailable.','outsider cannot recover unbound outline');
select throws_ok($$select public.admin_apply_ai_course(current_setting('test.retryId')::uuid)$$,'42501','Result unavailable.','receipt never bypasses access');
reset role;

-- Review stays content-based and version checked, with existing artwork rules.
select set_config('request.jwt.claim.sub','90640000-0000-4000-8000-000000000001',true);
select set_config('test.cid',current_setting('test.receipt')::jsonb->>'courseId',true);
select set_config('test.updated',(select updated_at::text from courses where id=current_setting('test.cid')),true);
select set_config('test.revs',(select jsonb_object_agg(id,draft_revision)::text from lessons where course_id=current_setting('test.cid')),true);
set local role authenticated;
select throws_ok($$select public.admin_review_ai_authored_course(current_setting('test.cid'),current_setting('test.updated')::timestamptz,current_setting('test.revs')::jsonb)$$,'22023','Add the course thumbnail and cover.','existing course artwork requirement enforced');
reset role;
select set_config('test.art',public.service_register_media(null,'registry/course-art.png','image/png',10,'Course artwork','An illustrative cover','Test-owned artwork',null,null)->>'id',true);
set local role authenticated;
select lives_ok($$select public.admin_set_ai_course_artwork(current_setting('test.cid'),current_setting('test.art')::uuid,'course_thumbnail')$$,'thumbnail uses permitted stored artwork');
select lives_ok($$select public.admin_set_ai_course_artwork(current_setting('test.cid'),current_setting('test.art')::uuid,'course_cover')$$,'cover added without generation or seeds');
reset role;
select set_config('test.updated',(select updated_at::text from courses where id=current_setting('test.cid')),true);
select set_config('test.revs',(select jsonb_object_agg(id,draft_revision)::text from lessons where course_id=current_setting('test.cid')),true);
set local role authenticated;
select throws_ok($$select public.admin_publish_ai_authored_course(current_setting('test.cid'),current_setting('test.updated')::timestamptz,current_setting('test.revs')::jsonb)$$,'22023','Review the course before publishing.','generation never bypasses explicit review');
select lives_ok($$select public.admin_review_ai_authored_course(current_setting('test.cid'),current_setting('test.updated')::timestamptz,current_setting('test.revs')::jsonb)$$,'course explicitly reviewed with optional media placeholders');
reset role;
select is((select text_approved_by::text from courses where id=current_setting('test.cid')),'90640000-0000-4000-8000-000000000001','review attribution persisted');
select set_config('test.revs',(select jsonb_object_agg(id,draft_revision)::text from lessons where course_id=current_setting('test.cid')),true);
select set_config('test.updated',(select updated_at::text from courses where id=current_setting('test.cid')),true);
set local role authenticated;
select lives_ok($$select public.admin_publish_ai_authored_course(current_setting('test.cid'),current_setting('test.updated')::timestamptz,current_setting('test.revs')::jsonb)$$,'reviewed course publishes through existing lesson boundary');
reset role;
select is((select count(*) from lessons where course_id=current_setting('test.cid') and published_snapshot is not null),2::bigint,'publication atomically snapshots all lessons');
-- Attached assets remain protected after text-only generation and review.
select set_config('test.updated',(select updated_at::text from courses where id=current_setting('test.cid')),true);
select set_config('test.revs',(select jsonb_object_agg(id,draft_revision)::text from lessons where course_id=current_setting('test.cid')),true);
update private.media_versions set revoked_at=now() where id=current_setting('test.art')::uuid;
set local role authenticated;
select throws_ok($$select public.admin_review_ai_authored_course(current_setting('test.cid'),current_setting('test.updated')::timestamptz,current_setting('test.revs')::jsonb)$$,'22023','Replace revoked media before reviewing.','revoked artwork blocks review');
select throws_ok($$select public.admin_set_ai_course_artwork(current_setting('test.cid'),current_setting('test.art')::uuid,'course_cover')$$,'42501','Media is not permitted for this course.','revoked asset cannot be reattached');
reset role;
update private.media_versions set revoked_at=null where id=current_setting('test.art')::uuid;
-- A failed atomic insertion keeps zero partial entities and the exact retry identity.
create function pg_temp.fail_course_block() returns trigger language plpgsql as $$begin raise exception 'Injected failure'; end$$;
create trigger course_fixture_failure before insert on lesson_content_blocks for each row execute function pg_temp.fail_course_block();
set local role authenticated;
select public.admin_prepare_ai_course_apply(current_setting('test.draftId')::uuid);
select throws_ok($$select public.admin_quote_ai_course('course_draft',null,current_setting('test.draftId')::uuid,0,0,'',true)$$,'PT409','Only unfinished, unapplied work can be retried.','uncertain application must be reconciled before retry generation');
select is(public.admin_apply_ai_course(current_setting('test.draftId')::uuid)->>'status','not_saved','partial-result application failure confirmed');
reset role;
select is((select count(*) from courses where id='course-ai-'||replace(current_setting('test.draftId'),'-','')),0::bigint,'failed application leaves no course or children');
drop trigger course_fixture_failure on lesson_content_blocks;
set local role authenticated;
select is(public.admin_apply_ai_course(current_setting('test.draftId')::uuid)->>'status','saved','confirmed failure can recover same partial-result save');
select public.admin_delete_ai_result(current_setting('test.outlineId')::uuid);
reset role;
select ok((select course_outline is null and candidate is null from private.ai_authoring_results where id=current_setting('test.outlineId')::uuid),'explicit deletion clears candidate and edited outline');
-- Organisation ownership, credit envelope and partial-stop release.
insert into organizations(id,slug,name,status,created_by) values('90640000-0000-4000-8000-000000000101','course-authoring-org','Course org','published','90640000-0000-4000-8000-000000000001');
insert into organization_memberships(organization_id,user_id,role,status) values('90640000-0000-4000-8000-000000000101','90640000-0000-4000-8000-000000000001','organisation_owner','active');
set local role authenticated;
select public.admin_upsert_organization_temporary_entitlement_grant(null,'90640000-0000-4000-8000-000000000101','granular_override',null,
 '{"ai_authoring_enabled":true,"ai_monthly_allocation":2000,"ai_hard_limit":2000,"ai_user_rate_limit_per_day":20,"ai_organization_concurrency_limit":3,"allowed_ai_operation_types":["ai_planner_new_course","ai_course_draft"],"allowed_ai_roles":["organisation_owner"]}',now()-interval '1 minute',now()+interval '1 day','Course fixture');
select set_config('test.orgoutline',public.admin_quote_ai_course('course_outline',current_setting('test.brief')::jsonb,null,null,0,'',false,'90640000-0000-4000-8000-000000000101')->>'id',true);
select public.admin_start_ai_page(current_setting('test.orgoutline')::uuid);
select public.admin_start_ai_page(current_setting('test.orgoutline')::uuid);
reset role;
select is((select sum(reserved_units) from organization_ai_usage_records where organization_id='90640000-0000-4000-8000-000000000101'),57::numeric,'one outline reservation, no duplicates or image credits');
select pg_temp.step(current_setting('test.orgoutline')::uuid,'begin');
select pg_temp.step(current_setting('test.orgoutline')::uuid,'checkpoint',current_setting('test.outline')::jsonb);
set local role authenticated;
select set_config('test.orgdraft',public.admin_quote_ai_course('course_draft',null,current_setting('test.orgoutline')::uuid,1,1)->>'id',true);
select is(public.admin_read_ai_results(current_setting('test.orgdraft')::uuid)->>'estimatedUnits','182','explicit one-question scope included in quote');
select public.admin_start_ai_page(current_setting('test.orgdraft')::uuid);
reset role;
select pg_temp.step(current_setting('test.orgdraft')::uuid,'begin');
select set_config('test.question','[{"prompt":"What comes first?","questionType":"single_choice","explanation":"Hear everyone before choosing.","xp":10,"options":[{"label":"Hear everyone","isCorrect":true},{"label":"Choose immediately","isCorrect":false}]}]',true);
select pg_temp.step(current_setting('test.orgdraft')::uuid,'checkpoint',jsonb_set(current_setting('test.lesson')::jsonb,'{questions}',current_setting('test.question')::jsonb));
set local role authenticated;
select public.admin_stop_ai_result(current_setting('test.orgdraft')::uuid);
reset role;
select pg_temp.step(current_setting('test.orgdraft')::uuid,'begin');
set local role authenticated;
select is(public.admin_read_ai_results(current_setting('test.orgdraft')::uuid)->>'stage','stopped','stop preserves validated checkpoint');
select is(public.admin_read_ai_results(current_setting('test.orgdraft')::uuid)->'credit'->>'used','141','settlement charges base plus only started lesson and question');
select is(public.admin_read_ai_results(current_setting('test.orgdraft')::uuid)->'credit'->>'released','41','never-started lesson and question allocation released');
select public.admin_prepare_ai_course_apply(current_setting('test.orgdraft')::uuid);
select set_config('test.orgreceipt',public.admin_apply_ai_course(current_setting('test.orgdraft')::uuid)::text,true);
select is(current_setting('test.orgreceipt')::jsonb->>'status','saved','organisation partial course applies');
reset role;
select is((select catalog_scope::text from courses where id=current_setting('test.orgreceipt')::jsonb->>'courseId'),'organization_private','materialized course stays organisation private');
select is((select organization_id::text from courses where id=current_setting('test.orgreceipt')::jsonb->>'courseId'),'90640000-0000-4000-8000-000000000101','materialized owner matches retained workspace');
select is((select count(*) from quiz_questions q join quizzes z on z.id=q.quiz_id join lessons l on l.id=z.lesson_id where l.course_id=current_setting('test.orgreceipt')::jsonb->>'courseId'),1::bigint,'only completed lesson quiz inserted');
update profiles set role='learner' where id='90640000-0000-4000-8000-000000000001';
set local role authenticated;
select lives_ok($$select public.admin_read_ai_results(current_setting('test.orgoutline')::uuid)$$,'organisation owner can recover their unbound outline');
select throws_ok($$select public.admin_read_ai_results(current_setting('test.retryId')::uuid)$$,'42501','Result unavailable.','organisation owner cannot recover platform result');
reset role;
update organization_memberships set status='suspended' where organization_id='90640000-0000-4000-8000-000000000101';
set local role authenticated;
select throws_ok($$select public.admin_apply_ai_course(current_setting('test.orgdraft')::uuid)$$,'42501','Result unavailable.','revoked membership blocks saved receipt');
reset role;

select * from finish();
rollback;
