begin;
create extension if not exists pgtap with schema extensions;
set local search_path=extensions,public,private;
select no_plan();
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data) values
('90660000-0000-4000-8000-000000000001','authenticated','authenticated','image-editor@example.test','{}','{}'),
('90670000-0000-4000-8000-000000000002','authenticated','authenticated','image-outsider@example.test','{}','{}');
insert into profiles(id,display_name,role) values ('90660000-0000-4000-8000-000000000001','Editor','admin'),('90670000-0000-4000-8000-000000000002','Outsider','learner') on conflict(id) do update set role=excluded.role;
insert into courses(id,slug,title,description,category,catalog_scope,status) values('image-course','image-course','Community choices','Fixture','Values','platform','draft');
insert into lessons(id,slug,course_id,title,status) values('image-lesson','image-lesson','image-course','Listening','draft');
insert into lesson_pages(id,lesson_id,page_number,title,page_type) values('image-page','image-lesson',1,'A listening circle','concept');
insert into lesson_content_blocks(page_id,block_type,sort_order,payload) values('image-page','image',1,'{"src":"","mediaIntent":{"version":1,"kind":"image","purpose":"Neighbors listening in a circle","aspectRatio":"16:9","required":false,"style":"inherit"}}');
select set_config('test.block',(select id::text from lesson_content_blocks where page_id='image-page'),true);
select set_config('test.style','{"preset":"photography","palette":"Blue","direction":"Natural light"}',true);
create function pg_temp.quote_image() returns uuid language sql as $$ select (public.admin_quote_ai_image('block',current_setting('test.block'),(public.admin_ai_image_setup('block',current_setting('test.block'))->>'revision')::bigint,'Neighbors listening in a circle','"inherit"','Neighbors taking turns listening')->>'id')::uuid $$;
create function pg_temp.image_step(p_id uuid,p_action text) returns jsonb language plpgsql as $$
declare j public.ai_generation_jobs;
begin
 select * into j from ai_generation_jobs where id=(select job_id from private.ai_authoring_results where id=p_id);
 if j.status='queued' then select * into j from public.service_claim_ai_page(p_id,'image-test'); end if;
 return public.service_ai_image_checkpoint(j.id,'image-test',j.lock_token,j.lock_version,p_action,jsonb_build_object('path','registry/authoring-'||p_id||'.png','size',100));
end $$;
select ok(not has_function_privilege('authenticated','public.service_ai_image_checkpoint(uuid,text,uuid,integer,text,jsonb)','execute'),'worker image checkpoint private to service');
select ok(not has_function_privilege('anon','public.admin_quote_ai_image(text,text,bigint,text,jsonb,text,text,uuid)','execute'),'anonymous quote denied');
select set_config('request.jwt.claim.sub','90660000-0000-4000-8000-000000000001',true);
set local role authenticated;
select throws_ok($$select pg_temp.quote_image()$$,'22023','Choose an image style and describe any custom direction.','no silent default style');
select lives_ok($$select public.admin_save_ai_image_style('image-course',current_setting('test.style')::jsonb)$$,'editor sets course style');
select set_config('test.image',pg_temp.quote_image()::text,true);
select is(public.admin_read_ai_results(current_setting('test.image')::uuid)->>'estimatedUnits','75','single image uses existing estimate');
select is(public.admin_read_ai_results(current_setting('test.image')::uuid)->'image'->'style',current_setting('test.style')::jsonb,'quote snapshots effective style');
select public.admin_save_ai_image_style('image-course','{"preset":"flat","palette":"Green","direction":""}');
select is(public.admin_read_ai_results(current_setting('test.image')::uuid)->'image'->'style',current_setting('test.style')::jsonb,'later default does not mutate accepted options');
reset role;
select is((select count(*) from ai_generation_jobs where prompt->>'operationId'=current_setting('test.image')),0::bigint,'style browsing and quote create no job');
set local role authenticated;
select lives_ok($$select public.admin_start_ai_page(current_setting('test.image')::uuid)$$,'image starts through existing metering lifecycle');
select public.admin_start_ai_page(current_setting('test.image')::uuid);
reset role;
select is((select count(*) from ai_generation_jobs where prompt->>'operationId'=current_setting('test.image')),1::bigint,'double start enqueues once');
select is((select job_type from ai_generation_jobs where prompt->>'operationId'=current_setting('test.image')),'media_assets','image uses established media job type');
select is(pg_temp.image_step(current_setting('test.image')::uuid,'begin')->>'aspectRatio','16:9','worker receives block shape');
select throws_ok($$select pg_temp.image_step(current_setting('test.image')::uuid,'begin')$$,'P0001','An earlier provider outcome is uncertain; do not replay it.','uncertain provider dispatch is not replayed');
select throws_ok($$select pg_temp.image_step(current_setting('test.image')::uuid,'ready')$$,'P0001','Image file is not durably stored.','provider URL alone cannot become ready');
insert into storage.objects(bucket_id,name) values('learning-media-private','registry/authoring-'||current_setting('test.image')||'.png');
select lives_ok($$select pg_temp.image_step(current_setting('test.image')::uuid,'ready')$$,'stored image registers before ready');
select is((select payload->>'src' from lesson_content_blocks where id::text=current_setting('test.block')),'','generation does not change target');
select set_config('test.version',(select id::text from private.media_versions where authoring_result_id=current_setting('test.image')::uuid),true);
set local role authenticated;
select is(public.admin_ai_image_setup('block',current_setting('test.block'))->'latestResult'->>'id',current_setting('test.image'),'chooser recovers exact contextual result');
select ok(exists(select 1 from jsonb_array_elements(public.admin_media_library(p_source=>'generated')->'assets') a where a->>'id'=current_setting('test.version')),'generated image discoverable');
select ok(exists(select 1 from jsonb_array_elements(public.admin_media_library(p_source=>'unused')->'assets') a where a->>'id'=current_setting('test.version')),'unused image discoverable');
select public.admin_prepare_ai_image_apply(current_setting('test.image')::uuid);
select is(public.admin_read_ai_results(current_setting('test.image')::uuid)->>'applicationState','checking','apply intent survives lost response');
select set_config('test.receipt',public.admin_apply_ai_image(current_setting('test.image')::uuid)::text,true);
select is(current_setting('test.receipt')::jsonb->>'status','saved','explicit Use image saves');
select is(public.admin_apply_ai_image(current_setting('test.image')::uuid),current_setting('test.receipt')::jsonb,'double use returns atomic receipt');
select ok(not exists(select 1 from jsonb_array_elements(public.admin_media_library(p_source=>'unused')->'assets') a where a->>'id'=current_setting('test.version')),'used image leaves unused filter');
select throws_ok($$select public.admin_manage_media(current_setting('test.version')::uuid,'delete')$$,'23514','This version is still used by content.','referenced generated file protected');
select set_config('test.stale',pg_temp.quote_image()::text,true);
select public.admin_start_ai_page(current_setting('test.stale')::uuid);
reset role;
select pg_temp.image_step(current_setting('test.stale')::uuid,'begin');
insert into storage.objects(bucket_id,name) values('learning-media-private','registry/authoring-'||current_setting('test.stale')||'.png');
select pg_temp.image_step(current_setting('test.stale')::uuid,'ready');
update lesson_content_blocks set payload=payload||'{"caption":"Newer edit"}' where id::text=current_setting('test.block');
set local role authenticated;
select public.admin_prepare_ai_image_apply(current_setting('test.stale')::uuid);
select is(public.admin_apply_ai_image(current_setting('test.stale')::uuid)->>'status','not_saved','stale image cannot overwrite newer draft');
select is(public.admin_read_ai_results(current_setting('test.stale')::uuid)->>'applicationState','not_saved','confirmed conflict recovered');
select public.admin_delete_ai_result(current_setting('test.stale')::uuid);
reset role;
select is((select count(*) from private.media_versions where authoring_result_id=current_setting('test.stale')::uuid),1::bigint,'closing/deleting result does not remove paid file');
select set_config('request.jwt.claim.sub','90670000-0000-4000-8000-000000000002',true);
set local role authenticated;
select throws_ok($$select public.admin_ai_image_setup('block',current_setting('test.block'))$$,'42501','Image destination unavailable.','outsider cannot read brief');
select throws_ok($$select public.admin_read_ai_results(current_setting('test.image')::uuid)$$,'42501','Result unavailable.','outsider cannot recover image');
select throws_ok($$select public.admin_apply_ai_image(current_setting('test.image')::uuid)$$,'42501','Image unavailable.','outsider cannot replay receipt');
reset role;
select set_config('request.jwt.claim.sub','90660000-0000-4000-8000-000000000001',true);
insert into organizations(id,slug,name,status,created_by) values('90660000-0000-4000-8000-000000000101','image-org','Image org','published','90660000-0000-4000-8000-000000000001');
insert into organization_memberships(organization_id,user_id,role,status) values('90660000-0000-4000-8000-000000000101','90660000-0000-4000-8000-000000000001','organisation_owner','active');
insert into courses(id,slug,title,description,category,catalog_scope,organization_id,status) values('image-org-course','image-org-course','Org images','Teaching','Values','organization_private','90660000-0000-4000-8000-000000000101','draft');
set local role authenticated;
select public.admin_upsert_organization_temporary_entitlement_grant(null,'90660000-0000-4000-8000-000000000101','granular_override',null,
 '{"ai_authoring_enabled":true,"ai_monthly_allocation":250,"ai_hard_limit":250,"max_storage_bytes":104857600,"ai_user_rate_limit_per_day":20,"ai_organization_concurrency_limit":3,"allowed_ai_operation_types":["ai_single_media_asset"],"allowed_ai_roles":["organisation_owner"]}',
 now()-interval '1 minute',now()+interval '1 day','Image fixture');
reset role;
insert into learning_media_assets(course_id,asset_type,placement,source,metadata,review_status,generation_status,sort_order) values('image-org-course','thumbnail','course_thumbnail','ai_generated','{"targetKind":"course_thumbnail","required":true}','draft','pending',0);
set local role authenticated;
select set_config('test.orgimage',public.admin_quote_ai_image('course_thumbnail','image-org-course',0,'A listening circle',current_setting('test.style')::jsonb,'Neighbors listening')->>'id',true);
select public.admin_start_ai_page(current_setting('test.orgimage')::uuid);
select public.admin_start_ai_page(current_setting('test.orgimage')::uuid);
reset role;
select is((select sum(reserved_units) from organization_ai_usage_records where organization_id='90660000-0000-4000-8000-000000000101'),75::numeric,'organization image reserves once');
select pg_temp.image_step(current_setting('test.orgimage')::uuid,'begin');
set local role authenticated;
select is(public.admin_stop_ai_result(current_setting('test.orgimage')::uuid)->>'stopRequested','true','stop during provider retains pending image');
reset role;
insert into storage.objects(bucket_id,name) values('learning-media-private','registry/authoring-'||current_setting('test.orgimage')||'.png');
select lives_ok($$select pg_temp.image_step(current_setting('test.orgimage')::uuid,'ready')$$,'completed stopped request retains paid result');
select is((select sum(final_charged_units) from organization_ai_usage_records where organization_id='90660000-0000-4000-8000-000000000101'),75::numeric,'provider image charged once');
set local role authenticated;
select public.admin_prepare_ai_image_apply(current_setting('test.orgimage')::uuid);
select is(public.admin_apply_ai_image(current_setting('test.orgimage')::uuid)->>'status','saved','course thumbnail supports explicit use');
reset role;
select is((select url from learning_media_assets where course_id='image-org-course' and placement='course_thumbnail'),(select thumbnail->>'src' from courses where id='image-org-course'),'generated thumbnail updates existing required cover identity');
set local role authenticated;
select set_config('test.orgstop',public.admin_quote_ai_image('course_cover','image-org-course',0,'A cover',current_setting('test.style')::jsonb,'A cover')->>'id',true);
select public.admin_start_ai_page(current_setting('test.orgstop')::uuid);
select is(public.admin_stop_ai_result(current_setting('test.orgstop')::uuid)->'credit'->>'released','75','stop before provider releases image credit');
reset role;
select is((select sum(final_charged_units) from organization_ai_usage_records where organization_id='90660000-0000-4000-8000-000000000101'),75::numeric,'Use image and stop do not add charges');
set local role authenticated;
select lives_ok($$select public.admin_ai_image_setup('lesson_thumbnail','image-lesson')$$,'lesson cover uses existing cover field');
select lives_ok($$select public.admin_ai_image_setup('page_cover','image-page')$$,'page cover resolves real saved destination');
reset role;
set local role authenticated;
select set_config('test.cover',public.admin_quote_ai_image('lesson_thumbnail','image-lesson',(public.admin_ai_image_setup('lesson_thumbnail','image-lesson')->>'revision')::bigint,'A cover',current_setting('test.style')::jsonb,'Cover example')->>'id',true);
select public.admin_start_ai_page(current_setting('test.cover')::uuid);
reset role;
select pg_temp.image_step(current_setting('test.cover')::uuid,'begin');
insert into storage.objects(bucket_id,name) values('learning-media-private','registry/authoring-'||current_setting('test.cover')||'.png');
select pg_temp.image_step(current_setting('test.cover')::uuid,'ready');
set local role authenticated;
select public.admin_prepare_ai_image_apply(current_setting('test.cover')::uuid);
select is(public.admin_apply_ai_image(current_setting('test.cover')::uuid)->>'status','saved','lesson_thumbnail explicitly applies through existing placement boundary');
reset role;
select ok((select cover_image->>'src' from lessons where id='image-lesson') like '/api/media/%','lesson_thumbnail uses managed registry reference');
set local role authenticated;
select set_config('test.cover',public.admin_quote_ai_image('page_cover','image-page',(public.admin_ai_image_setup('page_cover','image-page')->>'revision')::bigint,'A cover',current_setting('test.style')::jsonb,'Cover example')->>'id',true);
select public.admin_start_ai_page(current_setting('test.cover')::uuid);
reset role;
select pg_temp.image_step(current_setting('test.cover')::uuid,'begin');
insert into storage.objects(bucket_id,name) values('learning-media-private','registry/authoring-'||current_setting('test.cover')||'.png');
select pg_temp.image_step(current_setting('test.cover')::uuid,'ready');
set local role authenticated;
select public.admin_prepare_ai_image_apply(current_setting('test.cover')::uuid);
select is(public.admin_apply_ai_image(current_setting('test.cover')::uuid)->>'status','saved','page_cover explicitly applies through existing placement boundary');
reset role;
select ok((select cover_image->>'src' from lesson_pages where id='image-page') like '/api/media/%','page_cover uses managed registry reference');
set local role authenticated;
select set_config('test.cover',public.admin_quote_ai_image('course_cover','image-course',(public.admin_ai_image_setup('course_cover','image-course')->>'revision')::bigint,'A cover',current_setting('test.style')::jsonb,'Cover example')->>'id',true);
select public.admin_start_ai_page(current_setting('test.cover')::uuid);
reset role;
select pg_temp.image_step(current_setting('test.cover')::uuid,'begin');
insert into storage.objects(bucket_id,name) values('learning-media-private','registry/authoring-'||current_setting('test.cover')||'.png');
select pg_temp.image_step(current_setting('test.cover')::uuid,'ready');
set local role authenticated;
select public.admin_prepare_ai_image_apply(current_setting('test.cover')::uuid);
select is(public.admin_apply_ai_image(current_setting('test.cover')::uuid)->>'status','saved','course_cover explicitly applies through existing placement boundary');
select set_config('test.expired',public.admin_quote_ai_image('course_cover','image-course',0,'A cover',current_setting('test.style')::jsonb,'Course cover')->>'id',true);
reset role;
update private.ai_authoring_results set expires_at=now()-interval '1 second' where id=current_setting('test.expired')::uuid;
set local role authenticated;
select throws_ok($$select public.admin_start_ai_page(current_setting('test.expired')::uuid)$$,'PT409','This estimate expired. Check the cost again.','expired image quote cannot reserve credits');
select throws_ok($$select public.admin_save_ai_image_style('image-course','{"preset":"unknown","palette":"","direction":""}')$$,'22023','Choose an image style and describe any custom direction.','unsupported style rejected at RPC');
reset role;
update profiles set role='learner' where id='90660000-0000-4000-8000-000000000001';
delete from organization_memberships where organization_id='90660000-0000-4000-8000-000000000101';
set local role authenticated;
select throws_ok($$select public.admin_read_ai_results(current_setting('test.orgimage')::uuid)$$,'42501','Result unavailable.','revoked workspace editor loses retained image access');
select throws_ok($$select public.admin_media_library(p_organization_id=>'90660000-0000-4000-8000-000000000101',p_source=>'generated')$$,'42501','Media editor access required.','revoked access also removes generated library');
reset role;
select * from finish();
rollback;
