/* Revised draft supplied 12 September 2026; final copy approval pending. */
window.AuthCopy = {
  "brand": "project v/e",
  "switchLoginTitle": "Already have an account?",
  "switchLoginBody": "Sign in to continue your learning.",
  "switchSignupTitle": "Let curiosity lead.",
  "switchSignupBody": "Explore ideas, think for yourself and put what you learn into practice.",
  "returnWelcome": "Back to welcome",
  "xpLabel": "Your progress so far",
  "signupTitle": "Create your account",
  "signupXpTitle": "Keep what you’ve started",
  "signupOrgTitle": "First, create your account",
  "signupBody": "Learn for your own reasons. Earn XP along the way.",
  "signupXpBody": "Save your progress and XP, then keep learning with your own account.",
  "signupOrgBody": "Your account comes first. Then create a learning space shaped around your organisation’s goals.",
  "nameLabel": "Full name",
  "namePlaceholder": "Your full name",
  "emailLabel": "Email address",
  "emailPlaceholder": "you@example.com",
  "passwordLabel": "Password",
  "passwordPlaceholder": "Enter your password",
  "newPasswordLabel": "New password",
  "newPasswordPlaceholder": "Choose a new password",
  "passwordHelp": "Use at least 8 characters.",
  "show": "Show",
  "hide": "Hide",
  "showPassword": "Show password",
  "hidePassword": "Hide password",
  "termsLead": "I agree to the",
  "terms": "Terms",
  "termsJoin": "and",
  "privacyPolicy": "Privacy Policy",
  "signupAction": "Create account",
  "signupXpAction": "Create account & save progress",
  "signupOrgAction": "Create account & continue",
  "loginLink": "Sign in",
  "signupLink": "Create an account",
  "or": "or",
  "googleSignup": "Sign up with Google",
  "googleLogin": "Sign in with Google",
  "loginTitle": "Welcome back",
  "loginBody": "Pick up where you left off. There’s more to discover.",
  "loginXpBody": "Sign in to save this progress and XP to your account.",
  "loginOrgBody": "Sign in to continue setting up your organisation.",
  "loginAction": "Sign in",
  "remember": "Keep me signed in",
  "forgotLink": "Forgot password?",
  "forgotTitle": "Reset your password",
  "forgotBody": "Enter your account’s email address. We’ll send you a password reset link.",
  "forgotAction": "Send reset link",
  "backLogin": "Back to sign in",
  "resetSentTitle": "Check your inbox",
  "resetSentBody": "If an account exists for {email}, you’ll receive a password reset link.",
  "resetSentHelp": "Check your spam folder. If the email has not arrived, you can request another link.",
  "resendReset": "Send another reset link",
  "resetTitle": "Choose a new password",
  "resetBody": "Set a new password for your account.",
  "resetAction": "Save new password",
  "resetDoneTitle": "Password updated",
  "resetDoneBody": "Sign in with your new password to continue.",
  "confirmTitle": "Confirm your email",
  "confirmBody": "We’ve sent a confirmation link to {email}. Open it to verify your account.",
  "confirmHelp": "Check your spam folder, or request a new confirmation email.",
  "confirmResend": "Resend confirmation email",
  "changeEmail": "Use a different email",
  "confirmResent": "Another confirmation email is on its way.",
  "resetResent": "If an account exists for that email, another reset link is on its way.",
  "verifiedTitle": "Your email is confirmed",
  "verifiedBody": "Sign in to continue with your account.",
  "verifiedAction": "Continue to sign in",
  "expiredTitle": "This link has expired",
  "expiredBody": "Request a new link, then use the link in the most recent email.",
  "expiredAction": "Send a new link",
  "googleTitle": "Continue with Google",
  "googleBody": "Choose your Google account, then return here to continue.",
  "googleReturn": "Back to the form",
  "successTitle": "Your next step starts here",
  "successXpTitle": "A start worth building on",
  "successBody": "Explore a lesson, try a mission and find an idea to take into everyday life. Earn XP as you go.",
  "successXpBody": "Your progress and XP are saved. Keep learning and completing missions to work towards available rewards.",
  "savedXpLabel": "XP saved",
  "successRewards": "Explore rewards",
  "successLearn": "Continue learning",
  "orgSuccessTitle": "Now make space for your people",
  "orgSuccessBody": "Your account is ready. Give your organisation a name and start a learning space around your people and your goals.",
  "orgSuccessAction": "Set up your organisation",
  "rewardsTitle": "Put your XP to use",
  "rewardsBody": "Exchange your XP for available rewards when you have enough points. Each reward has its own point requirement and availability.",
  "rewardsBalance": "Your XP balance",
  "rewardsEmptyTitle": "No rewards to show yet",
  "rewardsEmptyBody": "Keep learning and check back to see what becomes available.",
  "learnTitle": "Find your next useful idea",
  "learnBody": "Build on what you know. Explore another lesson and find an idea to put into practice.",
  "learnAction": "Try another sample lesson",
  "nameError": "Enter your full name.",
  "emailError": "Enter a valid email address.",
  "passwordError": "Enter your password.",
  "passwordLengthError": "Use at least 8 characters for your password.",
  "termsError": "Agree to the Terms and Privacy Policy to continue.",
  "invalidLogin": "That email and password don’t match. Try again or reset your password.",
  "existingAccount": "There’s already an account with this email. Sign in or reset your password.",
  "connectionError": "We couldn’t connect. Check your connection and try again.",
  "securityError": "Complete the security check to continue.",
  "privacy": "Privacy",
  "support": "Support",
  "previewNotice": "Design preview only. Use made-up details. No real account is created, and sample XP cannot be redeemed.",
  "previewLabel": "Preview controls",
  "previewVerify": "Open sample confirmation link",
  "previewReset": "Open sample reset link",
  "previewGoogle": "Complete Google preview",
  "previewExpired": "Preview expired link",
  "previewError": "Preview connection error",
  "previewLoginError": "Preview incorrect password",
  "previewExisting": "Preview existing account",
  "previewSecurity": "Preview security check",
  "rewardsPreview": "Reward catalogue preview. The connected app will show its own available rewards.",
  "orgPreview": "Organisation setup continues in the connected app.",
  "pageTitle": "Project VE · Your account"
};
