import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {checked,mediaFixture} from '../support/media-browser';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j7l8AAAAASUVORK5CYII=','base64');
test('legacy media maps in context, keeps published content and reviews without a seed batch',async({browser,baseURL},info)=>{
 const f=await mediaFixture(browser,baseURL!);const page=await f.context.newPage();const jobs:string[]=[];
 try{
  const target=await f.lesson([{block_type:'text',payload:{body:'Listen to each neighbour before deciding.'}}]);
  checked(await f.service.from('courses').update({status:'draft',ai_generated:true,ai_text_status:'draft',ai_media_status:'not_started',ai_publish_status:'not_ready',intended_audience:'Community learners',learning_outcomes:['Listen before deciding.']}).eq('id',target.course));
  checked(await f.service.from('lessons').update({ai_generated:true,ai_text_status:'draft',ai_media_status:'not_started',quiz_requires_lesson_completion:false}).eq('id',target.lesson));
  const before=checked(await f.editor.from('lessons').select('published_snapshot').eq('id',target.lesson).single()).published_snapshot;
  const lessonPage=checked(await f.editor.from('lesson_pages').select('id').eq('lesson_id',target.lesson).single());
  const imageId=randomUUID(),orphanId=randomUUID();
  checked(await f.service.from('learning_media_assets').insert([{id:imageId,course_id:target.course,lesson_id:target.lesson,asset_type:'image',placement:'Listening circle',prompt:'Show people taking turns listening.',metadata:{targetKind:'page_block',targetPageId:lessonPage.id,required:true},sort_order:1},{id:orphanId,course_id:target.course,lesson_id:target.lesson,asset_type:'audio',placement:'Conversation example',script:'Two neighbours listen before deciding.',metadata:{required:true},sort_order:2}]));
  const jobId=randomUUID();jobs.push(jobId);
  checked(await f.service.from('ai_generation_jobs').insert({id:jobId,entity_type:'course',entity_id:target.course,job_type:'media_assets',status:'queued',prompt:{mode:'course_media'}}));
  let starts=0;await page.route('**/api/admin/ai/authoring',route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().action==='start'){starts++;return route.fulfill({status:503,json:{error:'Provider calls are disabled in this fixture.'}});}return route.continue();});
  await page.goto(`${baseURL}/admin/courses/${target.course}/settings`);
  await expect(page.getByText('Advanced settings',{exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:/Generate.*media/i})).toHaveCount(0);
  await page.getByRole('link',{name:'Earlier media and pending requests',exact:true}).click();
  await expect(page.getByText('Waiting for your choice',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Map earlier briefs',exact:true}).click();
  await expect(page.locator(`#brief-${imageId}`).getByText('Waiting for earlier work',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:'Cancel earlier request',exact:true}).click();
  await expect(page.getByText('Cancelled',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Map earlier briefs',exact:true}).click();
  await expect(page.locator(`#brief-${imageId}`).getByRole('link',{name:'Open media in its editor'})).toBeVisible();
  const orphan=page.locator(`#brief-${orphanId}`);await expect(orphan.getByText(/Needs a destination/)).toBeVisible();
  await orphan.getByRole('combobox').click();await page.getByRole('option',{name:/new optional media block/}).click();await orphan.getByRole('button',{name:'Map this brief'}).click();
  await expect(orphan.getByRole('link',{name:'Open media in its editor'})).toBeVisible();
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:info.outputPath('legacy-media-mobile.png'),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
  await page.locator(`#brief-${imageId}`).getByRole('link',{name:'Open media in its editor'}).click();
  await expect(page.locator(`#block-${imageId}`)).toBeVisible();await expect(page.getByText('Optional media',{exact:true})).toHaveCount(2);
  expect(checked(await f.editor.from('lessons').select('published_snapshot').eq('id',target.lesson).single()).published_snapshot).toEqual(before);
  const art=(await f.upload(png)).asset!;
  checked(await f.editor.rpc('admin_set_ai_course_artwork',{p_course:target.course,p_version:art.id,p_target:'course_thumbnail'}));
  checked(await f.editor.rpc('admin_set_ai_course_artwork',{p_course:target.course,p_version:art.id,p_target:'course_cover'}));
  await page.setViewportSize({width:1280,height:900});await page.goto(`${baseURL}/admin/courses/${target.course}/review`);
  await expect(page.getByRole('button',{name:'Approve reviewed course'})).toBeEnabled();
  await page.getByRole('button',{name:'Choose course cover',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('button',{name:'Generate with AI',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('checkbox',{name:'I have reviewed the course, lesson content, quiz answers and any attached media.'}).check();
  await page.getByRole('button',{name:'Approve reviewed course'}).click();
  await expect(page.getByRole('button',{name:'Publish course',exact:true})).toBeVisible();
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:info.outputPath('legacy-review-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'Publish course',exact:true}).click();
  await expect.poll(async()=>checked(await f.editor.from('courses').select('status').eq('id',target.course).single()).status).toBe('published');
  expect(starts).toBe(0);
  await page.goto(`${baseURL}/lessons/${target.lesson}`);await expect(page.getByText('Listen to each neighbour before deciding.',{exact:true})).toBeVisible();await expect(page.getByText('Optional media',{exact:true})).toHaveCount(0);
 }finally{if(jobs.length)checked(await f.service.from('ai_generation_jobs').delete().in('id',jobs));await f.cleanup();}
});
