"use client";
import {useState} from 'react';
import Link from 'next/link';
import {AdminSelect} from '@/components/admin/AdminSelect';
import {useMediaPicker} from '@/components/admin/MediaPickerProvider';
import {legacyMediaHref,type LegacyMediaWorkspace,type LegacyBrief} from '@/features/ai-generation/authoring/legacy-contracts';
import {aiButton} from './AiPageResult';
export function LegacyMediaReview({courseId,initial}:{courseId:string;initial:LegacyMediaWorkspace}) {
 const [data,setData]=useState(initial);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const {requestMedia}=useMediaPicker();
 async function refresh(){const response=await fetch(`/api/admin/ai/legacy-media?course=${encodeURIComponent(courseId)}`,{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error);setData(result);}
 async function act(body:Record<string,unknown>){setBusy(true);setError('');try{const response=await fetch('/api/admin/ai/legacy-media',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,courseId})});const result=await response.json();if(!response.ok)throw new Error(result.error);await refresh();}catch(e){setError(e instanceof Error?e.message:'The change could not be saved.');}finally{setBusy(false);}}
 async function chooseCover(brief:LegacyBrief){setError('');try{const picked=await requestMedia({title:'Choose an image',placementLabel:'Lesson cover',initialUrl:brief.url??'',initialAltText:brief.alt??'',imageTarget:{target:'lesson_thumbnail',targetId:brief.targetId!},imageDraft:{beforeAction:async()=>0,onApplied:()=>{void refresh();}},initialGenerationBrief:brief.brief,uploadContext:{assetType:'image',courseId,lessonId:brief.lessonId,placement:'lesson_thumbnail'}});if(picked&&!picked.alreadyApplied)await act({action:'cover',target:'lesson_thumbnail',targetId:brief.targetId,versionId:picked.assetVersionId??picked.url.split('/').pop()});}catch(e){setError(e instanceof Error?e.message:'The cover could not be saved.');}}
 return <div className="mx-auto max-w-3xl space-y-6 p-5">
  <Link href={`/admin/courses/${courseId}/review`} className="font-bold underline">Back to course review</Link>
  <h1 className="text-2xl font-black">Earlier media and pending requests</h1>
  <p className="text-sm">Your earlier briefs, selected assets and approvals are retained. Edit mapped media in its lesson or course cover. Empty inline media remains optional.</p>
  {error&&<p role="alert">{error}</p>}
  <div className="flex flex-wrap gap-3"><button className={aiButton} disabled={busy} onClick={()=>void act({action:'map'})}>Map earlier briefs</button><button className={aiButton} disabled={busy} onClick={()=>void refresh().catch(e=>setError(e.message))}>Refresh status</button></div>
  {data.jobs.length>0&&<section className="space-y-4" aria-label="Earlier generation requests"><h2 className="text-lg font-bold">Earlier generation requests</h2>{data.jobs.map(job=><article key={job.id} className="space-y-3 rounded-xl border p-4"><p className="font-bold">{job.decision==='pending'?'Waiting for your choice':job.decision==='cancel'?'Cancelled':job.status==='running'?'Creating earlier media':job.status==='completed'?'Earlier media complete':job.status==='failed'?'Earlier request failed':'Queued to continue'}</p><p className="text-sm">{job.creditStatus==='unmetered'?'0 credits':`${job.reserved??0} credits reserved · ${job.charged??0} charged · ${job.released??0} released`}</p>{job.decision==='pending'&&<><p className="text-sm">Continue the previously accepted batch with its existing reservation, or cancel it. {job.attempted?'Earlier work may already have incurred costs; cancelling does not refund attempted work.':'Cancelling before work starts releases the reservation.'}</p><div className="flex flex-wrap gap-3"><button className={aiButton} disabled={busy} onClick={()=>void act({action:'decide',jobId:job.id,decision:'continue'})}>Continue earlier request</button><button className={aiButton} disabled={busy} onClick={()=>void act({action:'decide',jobId:job.id,decision:'cancel'})}>Cancel earlier request</button></div></>}</article>)}</section>}
  <section className="space-y-4" aria-label="Earlier media briefs">{data.briefs.length===0&&<p>No earlier media briefs.</p>}{data.briefs.map(brief=><article id={`brief-${brief.id}`} key={brief.id} className="space-y-3 rounded-xl border p-4"><h2 className="font-bold">{brief.title.replaceAll('_',' ')}</h2><p className="text-sm whitespace-pre-wrap">{brief.brief}</p><p className="text-sm">{brief.status==='mapped'?'Mapped to its editor':brief.status==='deferred'?'Waiting for earlier work':'Needs a destination'} · {brief.url?'Selected asset retained':'Empty brief'} · {brief.review.replaceAll('_',' ')}</p>{brief.reason&&<p role="status" className="text-sm">{brief.reason}</p>}
    {brief.status==='mapped'?<div className="flex flex-wrap gap-3"><Link className="font-bold underline" href={legacyMediaHref(courseId,brief,data.destinations)}>Open media in its editor</Link>{brief.targetKind==='lesson_thumbnail'&&<button className={aiButton} onClick={()=>void chooseCover(brief)} disabled={busy}>Choose lesson cover</button>}</div>:brief.status!=='deferred'&&<form className="space-y-3" action={form=>{const selected=String(form.get('destination')??'');if(!selected)return;const destination=JSON.parse(selected);void act({action:'map',assetId:brief.id,kind:destination.kind,targetId:destination.id});}}><AdminSelect name="destination" placeholder="Choose the exact destination" options={data.destinations.filter(d=>!brief.lessonId||d.lessonId===brief.lessonId).map(d=>({label:d.label,value:JSON.stringify({kind:d.kind,id:d.id})}))}/><button className={aiButton} disabled={busy}>Map this brief</button></form>}
    <details className="text-xs"><summary className="cursor-pointer">Earlier provenance</summary><p>{brief.provenance.source} · {brief.provenance.provider??'No provider'} · {brief.provenance.model??'No model'}</p><p>The original brief and metadata remain in the protected migration audit.</p></details>
  </article>)}</section>
 </div>;
}
