export const entryCopy = {
  "WELCOME.001": "project v/e",
  "WELCOME.002": "Try a lesson",
  "WELCOME.003": "For organisations",
  "WELCOME.004": "Sign in",
  "WELCOME.005": "Learning for everyday life",
  "WELCOME.006": "Live what you learn.",
  "WELCOME.007": "Short lessons for clearer thinking and everyday choices. Put ideas into practice through missions and earn XP towards available rewards.",
  "WELCOME.008": "Try a lesson",
  "WELCOME.009": "Create an organisation",
  "WELCOME.010": "Start with something you recognise.",
  "WELCOME.011": "Who hasn’t had a say?",
  "WELCOME.012": "Would you pass this on?",
  "WELCOME.013": "Same invitation. Same chance?",
  "WELCOME.014": "Try this lesson",
  "WELCOME.015": "Choose a question. See where it takes you.",
  "WELCOME.016": "LEARN",
  "WELCOME.017": "PUT IT INTO PRACTICE",
  "WELCOME.018": "EARN REWARDS",
  "WELCOME.019": "One useful idea can change your next move.",
  "WELCOME.020": "Read a short lesson, explore a real-life scenario and see how XP works. No account needed until you’re ready to keep learning.",
  "WELCOME.021": "Try a sample. No account needed.",
  "WELCOME.022": "Learn",
  "WELCOME.023": "Try a question",
  "WELCOME.024": "Earn XP",
  "WELCOME.025": "Try the question",
  "WELCOME.026": "Read the lesson again",
  "WELCOME.027": "Save my progress",
  "WELCOME.028": "Create an account to keep your progress, continue learning and explore rewards.",
  "WELCOME.029": "Design preview: sample XP cannot be redeemed.",
  "WELCOME.030": "Sample lesson",
  "WELCOME.031": "Listening",
  "WELCOME.032": "Learning, together",
  "WELCOME.033": "Your people. Your purpose.",
  "WELCOME.034": "Give your organisation a space to learn, put ideas into practice and recognise progress, shaped around your people and your goals.",
  "WELCOME.035": "A team, a school, a community. Make it yours.",
  "WELCOME.036": "Make space without putting someone on the spot.",
  "WELCOME.037": "Start a conversation.",
  "WELCOME.038": "What makes it easier to speak up in your group? What makes it harder?",
  "WELCOME.039": "Put the idea into practice.",
  "WELCOME.040": "In your next group discussion, invite another perspective. Give people time to respond and room to pass.",
  "WELCOME.041": "An example of one lesson carried into conversation and everyday practice.",
  "WELCOME.042": "THE LESSON",
  "WELCOME.043": "THE CONVERSATION",
  "WELCOME.044": "THE MISSION",
  "WELCOME.045": "Choose your next step.",
  "WELCOME.046": "FOR YOU Keep learning Learn for your own reasons. Explore lessons, try missions and earn XP towards available rewards.",
  "WELCOME.047": "FOR YOUR PEOPLE Create an organisation Support learning around your own goals, in a shared space for your team, school or community.",
  "WELCOME.048": "Already have an account? Sign in",
  "WELCOME.049": "Design preview · Sample content",
  "WELCOME.050": "Live what you learn.",
  "WELCOME.extra.title": "Project VE · Live what you learn",
  "WELCOME.extra.description": "Explore short lessons, think for yourself and put ideas into practice. Learn on your own or with your organisation, and earn XP towards available rewards.",
  "WELCOME.extra.skip": "Skip to sample lesson",
  "WELCOME.extra.photoNote": "New perspectives.\nEveryday possibilities.",
  "SAMPLE.listen.title": "Who hasn’t had a say?",
  "SAMPLE.listen.category": "Listening",
  "SAMPLE.listen.lessonTitle": "Silence is not the same as agreement.",
  "SAMPLE.listen.lessonBody": "Someone who is quiet might agree, need more time or struggle to find a gap. Silence alone does not tell you which. Listening means creating room for another perspective, without making anyone feel they have to speak.",
  "SAMPLE.listen.lessonExample": "Your group is ready to choose a plan. Two people have done most of the talking. Try: “Before we decide, is there anything we have missed?” Pause, give others time, and leave room to pass.",
  "SAMPLE.listen.takeaway": "Create an opening. Leave a choice. Give the next voice your attention.",
  "SAMPLE.listen.question": "How would you open up the conversation?",
  "SAMPLE.listen.context": "Your group is about to make a decision. One person has not spoken, and you want to hear any views the group may be missing.",
  "SAMPLE.listen.idea": "Make space without putting someone on the spot.",
  "SAMPLE.listen.discussion": "What makes it easier to speak up in your group? What makes it harder?",
  "SAMPLE.listen.mission": "In your next group discussion, invite another perspective. Give people time to respond and room to pass.",
  "SAMPLE.listen.answer.A": "Ask everyone to give an opinion before you move on.",
  "SAMPLE.listen.answer.B": "Invite other views, with time to respond and room to pass.",
  "SAMPLE.listen.feedback.incorrect.heading": "Equal turns can still create pressure.",
  "SAMPLE.listen.feedback.incorrect.body": "Asking everyone to speak sounds inclusive, but it can put someone on the spot. Offer an invitation they can accept or pass on, then give them time.",
  "SAMPLE.listen.feedback.correct.heading": "An invitation, not an obligation.",
  "SAMPLE.listen.feedback.correct.body": "You have created a way into the conversation without demanding an answer. Now pause and give anyone who responds your attention.",
  "SAMPLE.think.title": "Would you pass this on?",
  "SAMPLE.think.category": "Clear thinking",
  "SAMPLE.think.lessonTitle": "Being believable is not the same as being true.",
  "SAMPLE.think.lessonBody": "A message can come from someone you trust and still contain a claim they have not checked. Knowing who passed it on is not the same as knowing where it began or what evidence supports it.",
  "SAMPLE.think.lessonExample": "A friend sends a screenshot saying a local event has been cancelled, but the date and source are missing. Before forwarding it, check the organiser’s original announcement and whether it refers to the right event and date.",
  "SAMPLE.think.takeaway": "Trace the source. Check the date and evidence. Then decide whether to share.",
  "SAMPLE.think.question": "Your group plans to attend. What next?",
  "SAMPLE.think.context": "Someone you trust sends a screenshot saying an event has been cancelled. It has no date or source, and nobody has checked with the organiser.",
  "SAMPLE.think.idea": "Give a convincing claim a closer look.",
  "SAMPLE.think.discussion": "What makes a claim feel trustworthy? What would actually help you check it?",
  "SAMPLE.think.mission": "Before sharing your next news story, find the original source and check whether it supports the claim.",
  "SAMPLE.think.answer.A": "Share it with a warning that it might be wrong.",
  "SAMPLE.think.answer.B": "Check the source and evidence before sharing.",
  "SAMPLE.think.feedback.incorrect.heading": "A warning is not a fact-check.",
  "SAMPLE.think.feedback.incorrect.body": "Saying you are unsure is honest, but the claim still reaches more people. Check the source and evidence before passing it on as news.",
  "SAMPLE.think.feedback.correct.heading": "Check first. Then decide.",
  "SAMPLE.think.feedback.correct.body": "An original source gives you something to assess, not automatic proof. Check its date and whether the evidence supports the claim before deciding to share.",
  "SAMPLE.act.title": "Same invitation. Same chance?",
  "SAMPLE.act.category": "Everyday fairness",
  "SAMPLE.act.lessonTitle": "Being invited is not always enough.",
  "SAMPLE.act.lessonBody": "Everyone can receive the same invitation without having the same chance to join. If the same person keeps missing out, look at the arrangement as well as the individual. What might be making participation difficult?",
  "SAMPLE.act.lessonExample": "Your group always meets in the afternoon. Someone with a regular commitment has missed two meetings. Instead of assuming they are not interested, ask what might help: another time, rotating meetings or a different way to contribute.",
  "SAMPLE.act.takeaway": "Notice who keeps missing out. Ask about the barrier. Explore what could change.",
  "SAMPLE.act.question": "How should the group choose its meeting time?",
  "SAMPLE.act.context": "Most people prefer afternoons. One member has a regular commitment then and has missed the last two meetings.",
  "SAMPLE.act.idea": "Look beyond the invitation to the chance to take part.",
  "SAMPLE.act.discussion": "Who keeps missing out on your group’s activities? What could you change to make joining easier?",
  "SAMPLE.act.mission": "Ask someone who rarely joins a group activity what would make it easier to take part. Explore one change together.",
  "SAMPLE.act.answer.A": "Hold a vote and use the most popular time.",
  "SAMPLE.act.answer.B": "Explore alternatives before choosing a time.",
  "SAMPLE.act.feedback.incorrect.heading": "A vote can miss a recurring barrier.",
  "SAMPLE.act.feedback.incorrect.body": "A majority vote tells you what most people prefer, but not what keeps someone from joining. Ask about the barrier and explore options before settling on a time.",
  "SAMPLE.act.feedback.correct.heading": "Understand the barrier before deciding.",
  "SAMPLE.act.feedback.correct.body": "You have not promised a perfect time for everyone. You have made room to consider another time, rotating meetings or a different way to contribute.",
  "LESSON.next": "Now try the idea in a real-life scenario.",
  "LESSON.takeawayLabel": "Take this with you",
  "QUIZ.correctPrefix": "That's right. {feedbackHeading}",
  "QUIZ.incorrectPrefix": "Not quite. Try again. {feedbackHeading}",
  "QUIZ.pause": "Take a moment. You can try again.",
  "XP.award": "+{awardXp} XP earned",
  "XP.alreadyEarned": "XP already earned",
  "XP.firstHeading": "You’ve put a new idea to the test.",
  "XP.repeatHeading": "Keep building on this idea.",
  "XP.explanation": "Lessons and missions earn XP you can use for rewards.",
  "XP.balanceLabel": "Your sample balance",
  "XP.balance": "{xp} XP",
  "XP.sampleLabel": "Sample XP",
  "XP.saveAction": "Save my progress",
  "XP.signupPrompt": "Create an account to keep your progress, continue learning and explore rewards.",
  "XP.previewOnly": "Design preview: sample XP cannot be redeemed.",
  "NOJS.answerSummary": "See the idea in practice",
  "NOJS.answer": "Invite other perspectives, give people time to respond and leave room to pass. Listening creates an opening; it does not demand an answer.",
  "ACCESS.welcome.1": "Project VE home",
  "ACCESS.welcome.2": "Main navigation",
  "ACCESS.welcome.3": "Explore a sample learning topic",
  "ACCESS.welcome.4": "People listening and sharing ideas around a table",
  "ACCESS.welcome.5": "Choose a sample topic",
  "ACCESS.welcome.6": "Your learning journey",
  "ACCESS.welcome.7": "Choose your answer",
  "AUTH.brand": "project v/e",
  "AUTH.switchLoginTitle": "Already have an account?",
  "AUTH.switchLoginBody": "Sign in to continue your learning.",
  "AUTH.switchSignupTitle": "Let curiosity lead.",
  "AUTH.switchSignupBody": "Explore ideas, think for yourself and put what you learn into practice.",
  "AUTH.returnWelcome": "Back to welcome",
  "AUTH.xpLabel": "Your progress so far",
  "AUTH.signupTitle": "Create your account",
  "AUTH.signupXpTitle": "Keep what you’ve started",
  "AUTH.signupOrgTitle": "First, create your account",
  "AUTH.signupBody": "Learn for your own reasons. Earn XP along the way.",
  "AUTH.signupXpBody": "Save your progress and XP, then keep learning with your own account.",
  "AUTH.signupOrgBody": "Your account comes first. Then create a learning space shaped around your organisation’s goals.",
  "AUTH.nameLabel": "Full name",
  "AUTH.namePlaceholder": "Your full name",
  "AUTH.emailLabel": "Email address",
  "AUTH.emailPlaceholder": "you@example.com",
  "AUTH.passwordLabel": "Password",
  "AUTH.passwordPlaceholder": "Enter your password",
  "AUTH.newPasswordLabel": "New password",
  "AUTH.newPasswordPlaceholder": "Choose a new password",
  "AUTH.passwordHelp": "Use at least 8 characters.",
  "AUTH.show": "Show",
  "AUTH.hide": "Hide",
  "AUTH.showPassword": "Show password",
  "AUTH.hidePassword": "Hide password",
  "AUTH.termsLead": "I agree to the",
  "AUTH.terms": "Terms",
  "AUTH.termsJoin": "and",
  "AUTH.privacyPolicy": "Privacy Policy",
  "AUTH.signupAction": "Create account",
  "AUTH.signupXpAction": "Create account & save progress",
  "AUTH.signupOrgAction": "Create account & continue",
  "AUTH.loginLink": "Sign in",
  "AUTH.signupLink": "Create an account",
  "AUTH.or": "or",
  "AUTH.googleSignup": "Sign up with Google",
  "AUTH.googleLogin": "Sign in with Google",
  "AUTH.loginTitle": "Welcome back",
  "AUTH.loginBody": "Pick up where you left off. There’s more to discover.",
  "AUTH.loginXpBody": "Sign in to save this progress and XP to your account.",
  "AUTH.loginOrgBody": "Sign in to continue setting up your organisation.",
  "AUTH.loginAction": "Sign in",
  "AUTH.remember": "Keep me signed in",
  "AUTH.forgotLink": "Forgot password?",
  "AUTH.forgotTitle": "Reset your password",
  "AUTH.forgotBody": "Enter your account’s email address. We’ll send you a password reset link.",
  "AUTH.forgotAction": "Send reset link",
  "AUTH.backLogin": "Back to sign in",
  "AUTH.resetSentTitle": "Check your inbox",
  "AUTH.resetSentBody": "If an account exists for {email}, you’ll receive a password reset link.",
  "AUTH.resetSentHelp": "Check your spam folder. If the email has not arrived, you can request another link.",
  "AUTH.resendReset": "Send another reset link",
  "AUTH.resetTitle": "Choose a new password",
  "AUTH.resetBody": "Set a new password for your account.",
  "AUTH.resetAction": "Save new password",
  "AUTH.resetDoneTitle": "Password updated",
  "AUTH.resetDoneBody": "Sign in with your new password to continue.",
  "AUTH.confirmTitle": "Confirm your email",
  "AUTH.confirmBody": "We’ve sent a confirmation link to {email}. Open it to verify your account.",
  "AUTH.confirmHelp": "Check your spam folder, or request a new confirmation email.",
  "AUTH.confirmResend": "Resend confirmation email",
  "AUTH.changeEmail": "Use a different email",
  "AUTH.confirmResent": "Another confirmation email is on its way.",
  "AUTH.resetResent": "If an account exists for that email, another reset link is on its way.",
  "AUTH.verifiedTitle": "Your email is confirmed",
  "AUTH.verifiedBody": "Sign in to continue with your account.",
  "AUTH.verifiedAction": "Continue to sign in",
  "AUTH.expiredTitle": "This link has expired",
  "AUTH.expiredBody": "Request a new link, then use the link in the most recent email.",
  "AUTH.expiredAction": "Send a new link",
  "AUTH.googleTitle": "Continue with Google",
  "AUTH.googleBody": "Choose your Google account, then return here to continue.",
  "AUTH.googleReturn": "Back to the form",
  "AUTH.successTitle": "Your next step starts here",
  "AUTH.successXpTitle": "A start worth building on",
  "AUTH.successBody": "Explore a lesson, try a mission and find an idea to take into everyday life. Earn XP as you go.",
  "AUTH.successXpBody": "Your progress and XP are saved. Keep learning and completing missions to work towards available rewards.",
  "AUTH.savedXpLabel": "XP saved",
  "AUTH.successRewards": "Explore rewards",
  "AUTH.successLearn": "Continue learning",
  "AUTH.orgSuccessTitle": "Now make space for your people",
  "AUTH.orgSuccessBody": "Your account is ready. Give your organisation a name and start a learning space around your people and your goals.",
  "AUTH.orgSuccessAction": "Set up your organisation",
  "AUTH.rewardsTitle": "Put your XP to use",
  "AUTH.rewardsBody": "Exchange your XP for available rewards when you have enough points. Each reward has its own point requirement and availability.",
  "AUTH.rewardsBalance": "Your XP balance",
  "AUTH.rewardsEmptyTitle": "No rewards to show yet",
  "AUTH.rewardsEmptyBody": "Keep learning and check back to see what becomes available.",
  "AUTH.learnTitle": "Find your next useful idea",
  "AUTH.learnBody": "Build on what you know. Explore another lesson and find an idea to put into practice.",
  "AUTH.learnAction": "Try another sample lesson",
  "AUTH.nameError": "Enter your full name.",
  "AUTH.emailError": "Enter a valid email address.",
  "AUTH.passwordError": "Enter your password.",
  "AUTH.passwordLengthError": "Use at least 8 characters for your password.",
  "AUTH.termsError": "Agree to the Terms and Privacy Policy to continue.",
  "AUTH.invalidLogin": "That email and password don’t match. Try again or reset your password.",
  "AUTH.existingAccount": "There’s already an account with this email. Sign in or reset your password.",
  "AUTH.connectionError": "We couldn’t connect. Check your connection and try again.",
  "AUTH.securityError": "Complete the security check to continue.",
  "AUTH.privacy": "Privacy",
  "AUTH.support": "Support",
  "AUTH.previewNotice": "Design preview only. Use made-up details. No real account is created, and sample XP cannot be redeemed.",
  "AUTH.previewLabel": "Preview controls",
  "AUTH.previewVerify": "Open sample confirmation link",
  "AUTH.previewReset": "Open sample reset link",
  "AUTH.previewGoogle": "Complete Google preview",
  "AUTH.previewExpired": "Preview expired link",
  "AUTH.previewError": "Preview connection error",
  "AUTH.previewLoginError": "Preview incorrect password",
  "AUTH.previewExisting": "Preview existing account",
  "AUTH.previewSecurity": "Preview security check",
  "AUTH.rewardsPreview": "Reward catalogue preview. The connected app will show its own available rewards.",
  "AUTH.orgPreview": "Organisation setup continues in the connected app.",
  "AUTH.pageTitle": "Project VE · Your account",
  "ACCESS.auth.2": "Account preview",
  "ACCESS.auth.3": "Show password",
  "ACCESS.auth.6": "Switch between sign in and create account",
  "ACCESS.auth.4": "Help and policies",
  "ACCESS.auth.5": "This form preview needs JavaScript. Return to the welcome page or read all screen text in the copy review. Open copy review"
} as const;
