const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const out=path.join(__dirname,'learning-journey');fs.mkdirSync(out,{recursive:true});
const results=[];
(async()=>{
  const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
  try{
    for(const profile of [{name:'desktop',width:1440,height:900},{name:'mobile',width:390,height:844},{name:'compact',width:360,height:640},{name:'reduced',width:390,height:844,reduce:true}]){
      const context=await browser.newContext({viewport:{width:profile.width,height:profile.height},reducedMotion:profile.reduce?'reduce':'no-preference'});
      await context.addInitScript(()=>{Element.prototype.requestPointerLock=()=>Promise.reject();Element.prototype.setPointerCapture=()=>{};Element.prototype.releasePointerCapture=()=>{};Document.prototype.exitPointerLock=()=>{}});
      const page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
      await page.goto('http://127.0.0.1:3341/',{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);
      await page.locator('[data-topic="think"]').click();
      await page.waitForFunction(()=>{const r=document.querySelector('#lesson-heading').getBoundingClientRect();return r.top>=0&&r.bottom<innerHeight&&document.activeElement.id==='lesson-heading'});
      assert.equal(await page.locator('#quiz-content').isVisible(),false);
      assert.match(await page.locator('#lesson-takeaway').innerText(),/Trace the source/);
      await page.screenshot({path:path.join(out,profile.name+'-lesson.png')});
      await page.locator('#start-quiz').click();
      await page.waitForFunction(()=>{const r=document.querySelector('#question-heading').getBoundingClientRect();return r.top>=0&&r.bottom<innerHeight&&document.activeElement.id==='question-heading'});
      await page.screenshot({path:path.join(out,profile.name+'-question.png')});
      await page.locator('[data-answer="0"]').click();
      assert.equal(await page.locator('#xp-result').isVisible(),false);
      assert.equal(await page.evaluate(()=>LearningRewards.balance()),0);
      assert.match(await page.locator('#feedback').innerText(),/Not quite. Try again./);
      await page.locator('[data-answer="1"]').click();
      await page.waitForFunction(()=>{const r=document.querySelector('#save-xp').getBoundingClientRect();return r.height>0&&r.top>=0&&r.bottom<=innerHeight&&document.activeElement.id==='xp-heading'});
      assert.equal(await page.locator('#xp-balance').innerText(),'10 XP');
      assert.equal(await page.locator('#xp-award').innerText(),'+10 XP');
      assert.equal(await page.evaluate(()=>document.activeElement.id),'xp-heading');
      await page.waitForFunction(()=>{const r=document.querySelector('#xp-result').getBoundingClientRect();return Math.abs(r.top+r.height/2-innerHeight/2)<30});
      await page.screenshot({path:path.join(out,profile.name+'-earned.png')});
      await page.locator('#save-xp').click();
      assert.equal(await page.locator('#signup-xp-balance').innerText(),'10 XP');
      assert.match(await page.locator('#entry-description').innerText(),/Sign up to save your XP/);
      assert.equal(await page.locator('#signup-xp').isVisible(),true);
      await page.screenshot({path:path.join(out,profile.name+'-signup.png')});
      await page.keyboard.press('Escape');
      assert.equal(await page.locator('#save-xp').evaluate(el=>el===document.activeElement),true);
      await page.locator('[data-answer="1"]').click();
      assert.equal(await page.locator('#xp-award').innerText(),'XP already earned');
      assert.equal(await page.locator('#xp-balance').innerText(),'10 XP');
      await page.locator('[data-topic="listen"]').click();
      assert.match(await page.locator('#lesson-body').innerText(),/Listening is more than/);
      await page.locator('#start-quiz').click();
      await page.locator('[data-answer="1"]').click();
      assert.equal(await page.locator('#xp-balance').innerText(),'20 XP');
      await page.locator('[data-topic="think"]').click();
      await page.locator('#start-quiz').click();
      await page.locator('[data-answer="1"]').click();
      assert.equal(await page.locator('#xp-balance').innerText(),'20 XP');
      await page.locator('#back-to-lesson').click();
      assert.equal(await page.locator('#lesson-content').isVisible(),true);
      assert.equal(await page.locator('#quiz-content').isVisible(),false);
      assert.equal(await page.evaluate(()=>LearningRewards.balance()),20);
      await page.locator('[data-topic="act"]').click();
      assert.match(await page.locator('#lesson-body').innerText(),/Fairness means/);
      assert.equal(await page.locator('#quiz-content').isVisible(),false);
      await page.locator('.entry-actions [data-entry="organisation"]').click();
      assert.equal(await page.locator('#signup-xp').isVisible(),false);
      assert.equal(new URL(await page.locator('#handoff-link').getAttribute('href')).searchParams.get('next'),'/org/create');
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
      assert.deepEqual(errors,[]);
      results.push({profile:profile.name,lessonBeforeQuiz:true,questionRevealed:true,readAgainPreservesXP:true,correctAnswerAwardsOnce:true,wrongAnswerAwardsNothing:true,signupRetainsBalance:true,noOverflow:true,errors});
      await context.close();
    }
    fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
  }finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
