const {chromium}=require('playwright-core');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const fs=require('node:fs');const path=require('node:path');
const out=path.join(__dirname,'auth');fs.mkdirSync(out,{recursive:true});
const origin='http://127.0.0.1:3341';
const results=[];
async function setup(browser,profile){const context=await browser.newContext({viewport:{width:profile.width,height:profile.height},reducedMotion:profile.reduce?'reduce':'no-preference'});await context.addInitScript(()=>{Element.prototype.requestPointerLock=()=>Promise.reject();Element.prototype.setPointerCapture=()=>{};Element.prototype.releasePointerCapture=()=>{};Document.prototype.exitPointerLock=()=>{}});return context;}
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
for(const profile of [{name:'desktop',width:1440,height:1000},{name:'mobile',width:390,height:844},{name:'compact',width:360,height:640},{name:'reduced',width:390,height:844,reduce:true}]){
const context=await setup(browser,profile);const page=await context.newPage();const errors=[];const outside=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin))outside.push(r.url())});
await page.goto(origin,{waitUntil:'load'});await page.locator('[data-topic="think"]').click();await page.locator('#start-quiz').click();await page.locator('[data-answer="0"]').click();assert.equal(await page.locator('#xp-result').isVisible(),false);await page.locator('[data-answer="1"]').click();await page.locator('#save-xp').click();await page.waitForURL(/auth.html/);await page.evaluate(()=>document.fonts.ready);
assert.match(await page.locator('#auth-title').innerText(),/Keep what you’ve started/);assert.equal(await page.locator('#auth-xp-value').innerText(),'10 XP');assert.equal(await page.getByText('Your starting point',{exact:true}).count(),0);
await page.evaluate(async()=>{await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})))});await page.screenshot({path:path.join(out,profile.name+'-signup.png'),fullPage:true});
await page.locator('#account-form button[type=submit]').click();assert.equal(await page.locator('[aria-invalid=true]').count(),4);
await page.locator('#name').fill('Preview Learner');await page.locator('#email').fill('learner@example.com');const password=randomUUID();await page.locator('#password').fill(password);await page.locator('[data-action=show-password]').click();assert.equal(await page.locator('#password').getAttribute('type'),'text');await page.locator('[data-action=show-password]').click();await page.locator('#terms').check();await page.locator('#account-form button[type=submit]').click();
assert.match(await page.locator('#auth-title').innerText(),/Confirm your email/);await page.evaluate(async()=>{await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})))});await page.screenshot({path:path.join(out,profile.name+'-confirm.png')});await page.locator('[data-action=resend]').click();assert.match(await page.locator('#auth-message').innerText(),/on its way/);await page.locator('[data-action=verified]').click();await page.locator('[data-action=login]').first().click();
await page.evaluate(async()=>{await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})))});await page.screenshot({path:path.join(out,profile.name+'-login.png'),fullPage:true});await page.locator('#password').fill(password);await page.locator('#account-form button[type=submit]').click();assert.match(await page.locator('#auth-title').innerText(),/A start worth building on/);assert.equal(await page.locator('.saved-balance strong').innerText(),'10 XP');await page.evaluate(async()=>{await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})))});await page.screenshot({path:path.join(out,profile.name+'-success.png')});await page.locator('[data-action=rewards]').click();assert.equal(await page.locator('.saved-balance strong').innerText(),'10 XP');
await page.locator('.auth-back').click();await page.waitForURL(/index.html$/);assert.equal(await page.locator('.hero').isVisible(),true);await page.reload();assert.equal(await page.locator('.hero').isVisible(),true);await page.locator('[data-topic="think"]').click();await page.locator('#start-quiz').click();await page.locator('[data-answer="1"]').click();assert.equal(await page.locator('#xp-balance').innerText(),'10 XP');
await page.goto(origin+'/auth.html?mode=login&intent=rewards');await page.locator('[data-action=forgot]').click();await page.locator('#email').fill('learner@example.com');await page.locator('#recovery-form button[type=submit]').click();await page.evaluate(async()=>{await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})))});await page.screenshot({path:path.join(out,profile.name+'-reset-sent.png')});await page.locator('[data-action=reset]').click();await page.locator('#password').fill(randomUUID());await page.locator('#recovery-form button[type=submit]').click();assert.match(await page.locator('#auth-title').innerText(),/Password updated/);await page.locator('[data-action=login]').click();await page.locator('#password').fill(randomUUID());await page.locator('#account-form button[type=submit]').click();assert.equal(await page.locator('.saved-balance strong').innerText(),'10 XP');
await page.goto(origin+'/auth.html?mode=signup&intent=organisation');assert.match(await page.locator('#auth-title').innerText(),/First, create your account/);await page.locator('#terms').check();await page.locator('[data-action=google]').click();await page.locator('[data-action=complete-google]').click();assert.match(await page.locator('#auth-title').innerText(),/make space for your people/);await page.locator('[data-action=organisation]').click();assert.equal(await page.locator('.state-actions a').getAttribute('href'),'http://localhost:3000/org/create');
await page.goto(origin+'/auth.html?mode=login');await page.locator('.preview-controls summary').click();await page.locator('[data-action=login-error]').click();assert.match(await page.locator('#auth-message').innerText(),/don’t match/);await page.evaluate(async()=>{await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})))});await page.screenshot({path:path.join(out,profile.name+'-error.png')});await page.locator('[data-action=expired]').click();assert.match(await page.locator('#auth-title').innerText(),/expired/);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);assert.deepEqual(outside,[]);results.push({profile:profile.name,signupConfirmationLogin:true,recoveryPreservesXP:true,welcomeRepeatAccess:true,xpAwardNotDuplicated:true,organisationContext:true,validationErrors:true,noExternalRequests:true});await context.close();
}
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
